/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnonymousProfile {
  'fullName' : string,
  'contactNumber' : string,
  'userClass' : UserClass,
}
export interface LeaderboardEntry {
  'principal' : Principal,
  'totalTests' : bigint,
  'fullName' : string,
  'bestScore' : bigint,
  'averageScore' : bigint,
}
export interface Question {
  'id' : string,
  'correctOption' : bigint,
  'createdAt' : Time,
  'optionImageData' : Array<string>,
  'questionImageData' : string,
}
export interface Test {
  'id' : string,
  'isPublished' : boolean,
  'subject' : [] | [string],
  'name' : string,
  'createdAt' : Time,
  'durationSeconds' : bigint,
  'questionIds' : Array<string>,
}
export interface TestResult {
  'id' : string,
  'userId' : Principal,
  'answers' : Array<bigint>,
  'submittedAt' : Time,
  'score' : bigint,
  'testId' : string,
}
export interface TestSummary {
  'id' : string,
  'subject' : [] | [string],
  'name' : string,
  'durationSeconds' : bigint,
  'questionCount' : bigint,
}
export type Time = bigint;
export type UserClass = { 'dropper' : null } |
  { 'eleventh' : null } |
  { 'twelfth' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / ADMIN: Add image-based question with base64 image data
   */
  'addQuestion' : ActorMethod<[string, Array<string>, bigint], string>,
  /**
   * / ADMIN: Get all users (anonymous profiles)
   */
  'adminGetAllUsers' : ActorMethod<[], Array<AnonymousProfile>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdmin' : ActorMethod<[], undefined>,
  /**
   * / ADMIN: Create test
   */
  'createTest' : ActorMethod<
    [string, [] | [string], bigint, Array<string>],
    string
  >,
  /**
   * / ADMIN: Get the admin principal (restricted to admin only)
   */
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  /**
   * / ADMIN: Get all questions (returns image-based Question schema)
   */
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  /**
   * / ADMIN: Get all test results sorted by submittedAt
   */
  'getAllResults' : ActorMethod<[], Array<TestResult>>,
  /**
   * / ADMIN: Get all tests (published and unpublished)
   */
  'getAllTests' : ActorMethod<[], Array<Test>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [AnonymousProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / ADMIN: Get leaderboard entries sorted by average score
   */
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyProfile' : ActorMethod<[], [] | [AnonymousProfile]>,
  'getMyResults' : ActorMethod<[], Array<TestResult>>,
  'getPublishedTests' : ActorMethod<[], Array<TestSummary>>,
  /**
   * / Requires authentication; admin can view any.
   */
  'getTestQuestions' : ActorMethod<[string], Array<Question>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [AnonymousProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProfileComplete' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[AnonymousProfile], undefined>,
  'saveUserProfile' : ActorMethod<[string, UserClass, string], undefined>,
  /**
   * / ADMIN: Publish/unpublish test
   */
  'setTestPublished' : ActorMethod<[string, boolean], undefined>,
  'submitTest' : ActorMethod<[string, Array<bigint>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];