/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TestSummary {
    id: string;
    subject?: string;
    name: string;
    durationSeconds: bigint;
    questionCount: bigint;
}
export interface LeaderboardEntry {
    principal: Principal;
    totalTests: bigint;
    fullName: string;
    bestScore: bigint;
    averageScore: bigint;
}
export type Time = bigint;
export interface AnonymousProfile {
    fullName: string;
    contactNumber: string;
    userClass: UserClass;
}
export interface Question {
    id: string;
    correctOption: bigint;
    questionImageUrl: string;
    createdAt: Time;
    optionImageUrls: Array<string>;
}
export interface TestResult {
    id: string;
    userId: Principal;
    answers: Array<bigint>;
    submittedAt: Time;
    score: bigint;
    testId: string;
}
export enum UserClass {
    dropper = "dropper",
    eleventh = "eleventh",
    twelfth = "twelfth"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    /**
     * / ADMIN: Add image-based question (requires 4 image URLs)
     */
    addQuestion(questionImageUrl: string, optionImageUrls: Array<string>, correctOption: bigint): Promise<string>;
    /**
     * / ADMIN: Get all users (anonymous profiles)
     */
    adminGetAllUsers(): Promise<Array<AnonymousProfile>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimAdmin(): Promise<void>;
    /**
     * / ADMIN: Create test
     */
    createTest(name: string, subject: string | null, durationSeconds: bigint, questionIds: Array<string>): Promise<string>;
    getAdminPrincipal(): Promise<Principal | null>;
    /**
     * / ADMIN: Get all questions (returns original image-based Question schema)
     */
    getAllQuestions(): Promise<Array<Question>>;
    /**
     * / ADMIN: Get all test results sorted by submittedAt
     */
    getAllResults(): Promise<Array<TestResult>>;
    getCallerUserProfile(): Promise<AnonymousProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / ADMIN: Get leaderboard entries sorted by average score
     */
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMyProfile(): Promise<AnonymousProfile | null>;
    getMyResults(): Promise<Array<TestResult>>;
    getPublishedTests(): Promise<Array<TestSummary>>;
    /**
     * / Requires authentication; admin can view any.
     */
    getTestQuestions(testId: string): Promise<Array<Question>>;
    getUserProfile(user: Principal): Promise<AnonymousProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isProfileComplete(): Promise<boolean>;
    saveCallerUserProfile(profile: AnonymousProfile): Promise<void>;
    saveUserProfile(fullName: string, userClass: UserClass, contactNumber: string): Promise<void>;
    /**
     * / ADMIN: Publish/unpublish test
     */
    setTestPublished(testId: string, published: boolean): Promise<void>;
    submitTest(testId: string, answers: Array<bigint>): Promise<bigint>;
}
import type { AnonymousProfile as _AnonymousProfile, TestSummary as _TestSummary, UserClass as _UserClass, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addQuestion(arg0: string, arg1: Array<string>, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1, arg2);
            return result;
        }
    }
    async adminGetAllUsers(): Promise<Array<AnonymousProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return result;
        }
    }
    async createTest(arg0: string, arg1: string | null, arg2: bigint, arg3: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTest(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTest(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async getAdminPrincipal(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return result;
        }
    }
    async getAllResults(): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResults();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<AnonymousProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyProfile(): Promise<AnonymousProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyResults(): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyResults();
            return result;
        }
    }
    async getPublishedTests(): Promise<Array<TestSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedTests();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedTests();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestQuestions(arg0: string): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestQuestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestQuestions(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<AnonymousProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isProfileComplete(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isProfileComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isProfileComplete();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: AnonymousProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_AnonymousProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_AnonymousProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveUserProfile(arg0: string, arg1: UserClass, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(arg0, to_candid_UserClass_n19(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(arg0, to_candid_UserClass_n19(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async setTestPublished(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTestPublished(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTestPublished(arg0, arg1);
            return result;
        }
    }
    async submitTest(arg0: string, arg1: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTest(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AnonymousProfile_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnonymousProfile): AnonymousProfile {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_TestSummary_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestSummary): TestSummary {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserClass_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserClass): UserClass {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AnonymousProfile]): AnonymousProfile | null {
    return value.length === 0 ? null : from_candid_AnonymousProfile_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    subject: [] | [string];
    name: string;
    durationSeconds: bigint;
    questionCount: bigint;
}): {
    id: string;
    subject?: string;
    name: string;
    durationSeconds: bigint;
    questionCount: bigint;
} {
    return {
        id: value.id,
        subject: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.subject)),
        name: value.name,
        durationSeconds: value.durationSeconds,
        questionCount: value.questionCount
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullName: string;
    contactNumber: string;
    userClass: _UserClass;
}): {
    fullName: string;
    contactNumber: string;
    userClass: UserClass;
} {
    return {
        fullName: value.fullName,
        contactNumber: value.contactNumber,
        userClass: from_candid_UserClass_n4(_uploadFile, _downloadFile, value.userClass)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dropper: null;
} | {
    eleventh: null;
} | {
    twelfth: null;
}): UserClass {
    return "dropper" in value ? UserClass.dropper : "eleventh" in value ? UserClass.eleventh : "twelfth" in value ? UserClass.twelfth : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnonymousProfile>): Array<AnonymousProfile> {
    return value.map((x)=>from_candid_AnonymousProfile_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestSummary>): Array<TestSummary> {
    return value.map((x)=>from_candid_TestSummary_n14(_uploadFile, _downloadFile, x));
}
function to_candid_AnonymousProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AnonymousProfile): _AnonymousProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserClass_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserClass): _UserClass {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fullName: string;
    contactNumber: string;
    userClass: UserClass;
}): {
    fullName: string;
    contactNumber: string;
    userClass: _UserClass;
} {
    return {
        fullName: value.fullName,
        contactNumber: value.contactNumber,
        userClass: to_candid_UserClass_n19(_uploadFile, _downloadFile, value.userClass)
    };
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserClass): {
    dropper: null;
} | {
    eleventh: null;
} | {
    twelfth: null;
} {
    return value == UserClass.dropper ? {
        dropper: null
    } : value == UserClass.eleventh ? {
        eleventh: null
    } : value == UserClass.twelfth ? {
        twelfth: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
