/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserClass = IDL.Variant({
  'dropper' : IDL.Null,
  'eleventh' : IDL.Null,
  'twelfth' : IDL.Null,
});
export const AnonymousProfile = IDL.Record({
  'fullName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'userClass' : UserClass,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Question = IDL.Record({
  'id' : IDL.Text,
  'correctOption' : IDL.Nat,
  'createdAt' : Time,
  'optionImageData' : IDL.Vec(IDL.Text),
  'questionImageData' : IDL.Text,
});
export const TestResult = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Nat),
  'submittedAt' : Time,
  'score' : IDL.Nat,
  'testId' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Principal,
  'totalTests' : IDL.Nat,
  'fullName' : IDL.Text,
  'bestScore' : IDL.Nat,
  'averageScore' : IDL.Nat,
});
export const TestSummary = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'questionCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addQuestion' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [IDL.Text],
      [],
    ),
  'adminGetAllUsers' : IDL.Func([], [IDL.Vec(AnonymousProfile)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimAdmin' : IDL.Func([], [], []),
  'createTest' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(AnonymousProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(AnonymousProfile)], ['query']),
  'getMyResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getPublishedTests' : IDL.Func([], [IDL.Vec(TestSummary)], ['query']),
  'getTestQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AnonymousProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([AnonymousProfile], [], []),
  'saveUserProfile' : IDL.Func([IDL.Text, UserClass, IDL.Text], [], []),
  'setTestPublished' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'submitTest' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserClass = IDL.Variant({
    'dropper' : IDL.Null,
    'eleventh' : IDL.Null,
    'twelfth' : IDL.Null,
  });
  const AnonymousProfile = IDL.Record({
    'fullName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'userClass' : UserClass,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Question = IDL.Record({
    'id' : IDL.Text,
    'correctOption' : IDL.Nat,
    'createdAt' : Time,
    'optionImageData' : IDL.Vec(IDL.Text),
    'questionImageData' : IDL.Text,
  });
  const TestResult = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Nat),
    'submittedAt' : Time,
    'score' : IDL.Nat,
    'testId' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Principal,
    'totalTests' : IDL.Nat,
    'fullName' : IDL.Text,
    'bestScore' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  const TestSummary = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'questionCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addQuestion' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [IDL.Text],
        [],
      ),
    'adminGetAllUsers' : IDL.Func([], [IDL.Vec(AnonymousProfile)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimAdmin' : IDL.Func([], [], []),
    'createTest' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Nat, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'getAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(AnonymousProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(AnonymousProfile)], ['query']),
    'getMyResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getPublishedTests' : IDL.Func([], [IDL.Vec(TestSummary)], ['query']),
    'getTestQuestions' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AnonymousProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([AnonymousProfile], [], []),
    'saveUserProfile' : IDL.Func([IDL.Text, UserClass, IDL.Text], [], []),
    'setTestPublished' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'submitTest' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };