/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnonymousProfile {
  'fullName' : string,
  'contactNumber' : string,
  'userClass' : UserClass,
}
export interface LeaderboardEntry {
  'principal' : Principal,
  'totalTests' : bigint,
  'fullName' : string,
  'bestScore' : bigint,
  'averageScore' : bigint,
}
export interface Question {
  'id' : string,
  'correctOption' : bigint,
  'questionImageUrl' : string,
  'createdAt' : Time,
  'optionImageUrls' : Array<string>,
}
export interface TestResult {
  'id' : string,
  'userId' : Principal,
  'answers' : Array<bigint>,
  'submittedAt' : Time,
  'score' : bigint,
  'testId' : string,
}
export interface TestSummary {
  'id' : string,
  'subject' : [] | [string],
  'name' : string,
  'durationSeconds' : bigint,
  'questionCount' : bigint,
}
export type Time = bigint;
export type UserClass = { 'dropper' : null } |
  { 'eleventh' : null } |
  { 'twelfth' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Adds a question. Admin only.
   */
  'addQuestion' : ActorMethod<[string, Array<string>, bigint], string>,
  /**
   * / Returns all user profiles. Admin only.
   */
  'adminGetAllUsers' : ActorMethod<[], Array<AnonymousProfile>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Claims admin rights if no admin exists yet; the first caller becomes the permanent admin.
   * / Subsequent calls from a different principal are rejected.
   */
  'claimAdmin' : ActorMethod<[], undefined>,
  /**
   * / Creates a test. Admin only.
   */
  'createTest' : ActorMethod<
    [string, [] | [string], bigint, Array<string>],
    string
  >,
  /**
   * / Returns the current admin principal. Publicly readable so the frontend can check.
   */
  'getAdminPrincipal' : ActorMethod<[], [] | [Principal]>,
  /**
   * / Returns all questions. Admin only.
   */
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  /**
   * / Returns all test results. Admin only.
   */
  'getAllResults' : ActorMethod<[], Array<TestResult>>,
  /**
   * / Returns the caller's own profile. Requires authenticated user.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [AnonymousProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Returns aggregated stats for all users sorted by average score descending. Admin only.
   */
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  /**
   * / Returns the caller's own profile (anonymous shape). Requires authenticated user.
   */
  'getMyProfile' : ActorMethod<[], [] | [AnonymousProfile]>,
  /**
   * / Returns all test results for the caller (most recent first). Requires authenticated user.
   */
  'getMyResults' : ActorMethod<[], Array<TestResult>>,
  /**
   * / Returns summaries of all published tests. Available to any caller (no auth required).
   */
  'getPublishedTests' : ActorMethod<[], Array<TestSummary>>,
  /**
   * / Returns questions for a published test. Requires authenticated user (or admin).
   */
  'getTestQuestions' : ActorMethod<[string], Array<Question>>,
  /**
   * / Fetches another user's profile. Caller can view their own; admins can view any.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [AnonymousProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Returns whether the caller has completed profile setup. Requires authenticated user.
   */
  'isProfileComplete' : ActorMethod<[], boolean>,
  /**
   * / Saves the caller's own profile. Requires authenticated user.
   */
  'saveCallerUserProfile' : ActorMethod<[AnonymousProfile], undefined>,
  /**
   * / Saves or updates the caller's profile. Requires authenticated user.
   */
  'saveUserProfile' : ActorMethod<[string, UserClass, string], undefined>,
  /**
   * / Publishes or unpublishes a test. Admin only.
   */
  'setTestPublished' : ActorMethod<[string, boolean], undefined>,
  /**
   * / Submits answers for a test, stores the result, and returns the score. Requires authenticated user.
   */
  'submitTest' : ActorMethod<[string, Array<bigint>], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];